# Indexing and slicing

In [2]:
import numpy as np
a = np.arange(10)
a
a[0], a[2], a[-1]

(0, 2, 9)

In [3]:
a[::-1] #when you use a[::-1], Python creates a new sequence with all elements from a, but in reverse order.

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
a = np.diag(np.arange(3)) #  np.arange(3) generates a NumPy array containing values from 0 to 2 (exclusive), which is [0, 1, 2]. The arange function creates a range of values.np.diag(...): The np.diag function is used to create a diagonal matrix from the input values. In this case, it takes the NumPy array [0, 1, 2] as input.
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [6]:
a[2,2]

2

In [7]:
a[1,1]

1

In [8]:
a[2,1]

0

# 1.3.2. Numerical operations on arrays

In [12]:
a = np.array([1,2,3,4])
a + 3

array([4, 5, 6, 7])

In [13]:
a ** 3

array([ 1,  8, 27, 64], dtype=int32)

In [16]:
a = np.array([1, 2, 3, 4])

b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

# Basic reductions

In [18]:
x = np.array([1, 2, 3, 4]) #adds all the values inside
np.sum(x)

10

In [19]:
x.min()

1

In [20]:
x.max()

4